# Generated by Django 2.1.5 on 2021-07-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_auto_20210702_1727'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interested_domains',
            field=models.ManyToManyField(blank=True, null=True, to='courses.ExamDomain'),
        ),
    ]
