# Generated by Django 2.1.5 on 2021-09-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210904_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='total_cities',
        ),
    ]
