# Generated by Django 2.1.5 on 2021-11-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20211026_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_verified',
            field=models.BooleanField(default=True),
        ),
    ]
