# Generated by Django 2.1.5 on 2021-11-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_account_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
