# Generated by Django 2.1.5 on 2022-03-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrystatecity', '0001_initial'),
        ('profiles', '0009_auto_20211116_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('head_contact_no', models.CharField(blank=True, max_length=12, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('registered', models.BooleanField(default=0, help_text='field to identify institutes which are registered by institute manager')),
                ('school_code', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('pin', models.CharField(blank=True, max_length=100, null=True)),
                ('std', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countrystatecity.Cities')),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Institute')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countrystatecity.States')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute', to='profiles.Institute'),
        ),
    ]
