# Generated by Django 2.1.5 on 2022-03-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20220308_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituteaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='instituteaddress',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='instituteaddress',
            name='state',
        ),
        migrations.AddField(
            model_name='institute',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.City'),
        ),
        migrations.AddField(
            model_name='institute',
            name='pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.State'),
        ),
        migrations.AddField(
            model_name='institute',
            name='std',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='InstituteAddress',
        ),
    ]
