# Generated by Django 2.1.5 on 2022-03-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20220310_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='std',
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
