# Generated by Django 2.1.5 on 2022-03-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20220310_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='school_code',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
