# Generated by Django 2.1.5 on 2022-04-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20220311_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logout_updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
