# Generated by Django 2.1.5 on 2022-04-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20220407_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='logout_updated_on',
        ),
    ]
