# Generated by Django 2.1.5 on 2022-04-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_remove_profile_logout_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logout_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
