# Generated by Django 2.1.5 on 2022-10-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSeasson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seassion_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
