AWSTemplateFormatVersion: '2010-09-09'
Description: roles and policies

Parameters:
  Prefix:
    Type: String
    Default: 'mmp'

Resources:

  # This role allows ECS tasks to access other AWS resources / APIs
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Prefix}-AmazonECSTASKRole"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}-AmazonECSTASKRole"

  AmazonECSAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Prefix}-AmazonECSAutoScalingRole"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [application-autoscaling.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Policies:
        - PolicyName: !Sub "${Prefix}-AmazonECSAutoScalingRolePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecs:DescribeServices
                  - ecs:UpdateService
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:DeleteAlarms
                Resource:
                  - "*"

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs-tasks.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: !Sub "${Prefix}-AmazonECSTaskExecutionRolePolicy"
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                # ECS Tasks to download images from ECR
                - 'ecr:GetAuthorizationToken'
                - 'ecr:BatchCheckLayerAvailability'
                - 'ecr:GetDownloadUrlForLayer'
                - 'ecr:BatchGetImage'
                # ECS tasks to upload logs to CloudWatch
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource: '*'

Outputs:

  AmazonECSTASKRole:
    Description: ECS Task Role
    Value: !GetAtt 'ECSTaskRole.Arn'
    Export:
      Name: !Sub "${Prefix}-AmazonECSTASKRole"

  ECSTaskExecutionRole:
    Description: ECS Task Execution Role
    Value: !GetAtt 'ECSTaskExecutionRole.Arn'
    Export:
      Name: !Sub "${Prefix}-ECSTaskExecutionRole"

  AmazonECSAutoScalingRole:
    Description: ECS Task AAutoscaling Role
    Value: !GetAtt 'AmazonECSAutoScalingRole.Arn'
    Export:
      Name: !Sub "${Prefix}-AmazonECSAutoScalingRole"
