# Generated by Django 2.1.5 on 2022-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20220429_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
