# Generated by Django 2.1.5 on 2022-04-29 15:34

from django.db import migrations, models
import notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notifications_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=notification.models.image_upload_to),
        ),
    ]
