# Generated by Django 2.1.5 on 2022-05-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0150_auto_20220502_1149'),
        ('courses', '0078_selfassessexamquestions_is_compulsory'),
        ('notification', '0005_auto_20220429_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Batch'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Exam'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='mentor_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.MentorPapers'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Question'),
        ),
    ]
