from django.contrib import admin

# Register your models here.
from . import models

admin.site.register(models.QuestionTag)
admin.site.register(models.Comprehensions)
admin.site.register(models.QuestionContent)
admin.site.register(models.Solution)
admin.site.register(models.Question)
admin.site.register(models.QuestionLanguage)
admin.site.register(models.McqTestCase)
admin.site.register(models.FillUpSolution)
admin.site.register(models.LearnerHistory)
admin.site.register(models.LearnerPapers)
admin.site.register(models.PaperInstructions)
admin.site.register(models.TrueFalseSolution)
admin.site.register(models.FillUpWithOption)
admin.site.register(models.AnswerPaper)
admin.site.register(models.UserAnswer)
admin.site.register(models.LearnerExamHistory)
admin.site.register(models.StringTestCase)
admin.site.register(models.SharedPapers)
admin.site.register(models.LearnerBookmarks)
admin.site.register(models.LearnerExamSubjects)
admin.site.register(models.LearnerExamChapters)
admin.site.register(models.LearnerExamPracticeSubjects)
admin.site.register(models.LearnerExamPracticeChapters)
admin.site.register(models.LearnerExamPaperSubjects)
admin.site.register(models.LearnerExamPaperChapters)
admin.site.register(models.LearnerExamPaperHistory)
admin.site.register(models.LearnerExamPracticeHistory)
admin.site.register(models.TemporaryLearnerBookmarks)
admin.site.register(models.LearnerQuery)
admin.site.register(models.QuestionIdentifiers)
admin.site.register(models.Batch)
admin.site.register(models.LearnerBatches)
admin.site.register(models.BatchTotalActualPapers)
admin.site.register(models.BatchTotalPracticePapers)
admin.site.register(models.MentorPapers)
admin.site.register(models.MentorPaperAnswerPaper)
admin.site.register(models.LearnerBatchHistory)
admin.site.register(models.ContactUs)
admin.site.register(models.ReportedErrorneousQuestion)
admin.site.register(models.FAQ)
admin.site.register(models.LearnerBlockedBatches)
admin.site.register(models.UserSubjectiveAnswerImage)
admin.site.register(models.MockPaperExamDetails)
admin.site.register(models.MockPaperSubjectDetails)
admin.site.register(models.MockPaperSubjectQuestionTypeDetails)
admin.site.register(models.TemporaryMentorPaperReplaceQuestions)
admin.site.register(models.LearnerTotalActualPapers)
admin.site.register(models.LearnerTotalPracticePapers)
admin.site.register(models.TemporaryMentorPracticeReplaceQuestions)
admin.site.register(models.LearnerExamGoals)
admin.site.register(models.SelfAssessExamAnswerPaper)
admin.site.register(models.SelfAssessUserAnswer)
admin.site.register(models.ChapterMasterFTag)
admin.site.register(models.TemporaryPaperSubjectQuestionDistribution)
admin.site.register(models.InstituteClassRoom)
admin.site.register(models.UserClassRoom)
admin.site.register(models.LearnerExamGoalPath)
admin.site.register(models.GoalPathLearnChapterHistory)
admin.site.register(models.GoalPathLearnChapterHintHistory)
admin.site.register(models.GoalPathReviseChapterHistory)
admin.site.register(models.GoalPathReviseChapterHintHistory)
admin.site.register(models.UnregisteredMentorBatch)
admin.site.register(models.StudentInstituteChangeInvitation)
admin.site.register(models.MentorBookmarks)
admin.site.register(models.MentorExamChapters)
admin.site.register(models.MentorExamSubjects)

#mmp_school models defined in content
admin.site.register(models.SchoolSeasson)
admin.site.register(models.BranchSchool)
admin.site.register(models.GoalAssessmentExamAnswerPaper)
admin.site.register(models.GoalAssessmentExamPaperInstructions)