from django.urls import path
from . import views as contennt_views
from . import create_question_bulk_view

urlpatterns = [
    path('bulk-upload-questions/',
         contennt_views.BulkUploadQuestion.as_view(), name='bulk-question'),
    path('question/', contennt_views.QuestionViewSet.as_view(), name='question'),
    path('create_question/',
         contennt_views.CreateQuestion.as_view(), name='create_question'),
    path('create_question_in_bulk/',
         create_question_bulk_view.BulkCreateQuestion.as_view(), name='create_question_in_bulk'),
    path('bulk_edit_question/',
         contennt_views.BulkEditQuestion.as_view(), name='bulk_edit_question'),
    path('questionlanguage/', contennt_views.QuestionLanguageViewSet.as_view(),
         name='questionlanguage'),
    path('question/<pk>/', contennt_views.EditQuestionViewSet.as_view(),
         name='editquestion'),
    path('questioninpaper/<pk>/', contennt_views.FetchQuestionByIdPaperViewSet.as_view(),
         name='questioninpaper'),
    path('filterquestion/', contennt_views.FetchQuestionsByFilterView.as_view(),
         name='filterquestion'),
    path('fetchquestionstagwise/', contennt_views.FetchQuestionsByTagsViewSet.as_view(),
         name='fetchquestionstagwise'),
    path('questionscounttypetagwise/', contennt_views.QuestionCountByTypeAndTagsViewSet.as_view(),
         name='questionscounttypetagwise'),
    path('questioncontent/', contennt_views.QuestionContentViewSet.as_view(),
         name='questioncontent'),
    path('questioncontent/<pk>/', contennt_views.EditQuestionContentViewSet.as_view(),
         name='editquestioncontent'),
    path('solution/', contennt_views.SolutionViewSet.as_view(), name='solution'),
    path('solution/<pk>/', contennt_views.EditSolutionViewSet.as_view(),
         name='editsolution'),
    path('fillupsolution/', contennt_views.FillUpSolutionViewSet.as_view(),
         name='fillupsolution'),
    path('fillupsolution/<pk>/', contennt_views.EditFillUpViewSet.as_view(),
         name='editfillupsolution'),
    path('stringtestcasesolution/', contennt_views.StringTestCaseViewSet.as_view(),
         name='stringtestcasesolution'),
    path('stringtestcasesolution/<pk>/', contennt_views.EditStringTestCaseViewSet.as_view(),
         name='editstringtestcasesolution'),
    path('mcqtestcase/', contennt_views.MCQTestCaseViewSet.as_view(),
         name='mcqtestcase'),
    path('mcqtestcase/<pk>/', contennt_views.EditMCQViewSet.as_view(),
         name='editmcqtestcase'),
    path('questiontag/', contennt_views.QuestionTagViewSet.as_view(),
         name='questiontag'),
    path('questiontag/<pk>/', contennt_views.EditQuestionTagViewSetViewSet.as_view(),
         name='editquestiontag'),
    path('searchquestiontag/', contennt_views.SearchQuestionTagViewSetViewSet.as_view(),
         name='searchquestiontag'),
    path('learnerhistory/', contennt_views.LearnerHistoryViewSet.as_view(),
         name='learnerhistory'),
    path('learnerpapers/', contennt_views.FetchLearnerPapersViewSet.as_view(),
         name='learnerpapers'),
    path('learnerpapers/<pk>/', contennt_views.FetchLearnerPapersByIdViewSet.as_view(),
         name='viewlearnerpapers'),
    path('goalpapers/<pk>/', contennt_views.FetchGoalPapersByIdViewSet.as_view(),
         name='viewlearnerpapers'),
    path('goalpapersshort/<pk>/', contennt_views.FetchShortGoalPapersByIdViewSet.as_view(),
         name='viewlearnerpapersshort'),
    path('paperinstructions/', contennt_views.PapersInstructionsViewSet.as_view(),
         name='paperinstructions'),
    path('goalpaperinstructions/', contennt_views.GoalPaperInstructionsViewSet.as_view(),
         name='paperinstructions'),
    path('fillwithoption/', contennt_views.FillUpWithOptionCaseViewSet.as_view(),
         name='fillwithoption'),
    path('fillwithoption/<pk>/', contennt_views.EditFillUpWithOptionViewSet.as_view(),
         name='editfillwithoption'),
    path('booleansolution/', contennt_views.BooleanTypeViewSet.as_view(),
         name='booleansolution'),
    path('booleansolution/<pk>/', contennt_views.EditBooleanTypeViewSet.as_view(),
         name='editbooleansolution'),
    path('assessmentpaper_questions/<int:assessmentpaper_id>/',contennt_views.QuestionAssessmentPaperView.as_view(), name='api_assessmentpaper_questions'),
    path('process_assessmentpaper_postsubmit/<int:assessmentpaper_id>/',contennt_views.ProcessAssessmentPaperPostSubmitView.as_view(), name='process_assessmentpaper_postsubmit'),
    path('post_answer/', contennt_views.PostAnswerView.as_view(), name='api_post_answer'),
    path('post_answer_image/', contennt_views.SubjectiveAnswerImageView.as_view(), name='post_answer_image'),
    path('assessmentpaper_report/<int:assessmentpaper_id>/',contennt_views.AssessmentPaperReportView.as_view(), name='api_assessmentpaper_report'),
    path('goalassessmentpaper_questions/<int:assessmentpaper_id>/',contennt_views.GoalQuestionAssessmentPaperView.as_view(), name='api_goalassessmentpaper_questions'),
    path('process_goalassessmentpaper_postsubmit/<int:assessmentpaper_id>/',contennt_views.GoalAssessmentPaperPostSubmitView.as_view(), name='process_goalassessmentpaper_postsubmit'),
    path('post_goal_paper_answer/', contennt_views.GoalAssessmentPostAnswerView.as_view(), name='api_post_goal_paper_answer'),
    path('goalassessmentpaper_report/<int:assessmentpaper_id>/',contennt_views.GoalAssessmentPaperReportView.as_view(), name='api_assessmentpaper_report'),
    path('linklearnerpapers/', contennt_views.SharedLearnerPaperLinkingView.as_view(),
         name='viewlinklearnerpapers'),
    path('learnerexamhistory/', contennt_views.LearnerExamHistoryViewSet.as_view(),
         name='learnerexamhistory'),
    path('learnerexampracticehistory/', contennt_views.LearnerExamPracticeHistoryViewSet.as_view(),
         name='learnerexampracticehistory'),
    path('learnerexampaperhistory/', contennt_views.LearnerExamPaperHistoryViewSet.as_view(),
         name='learnerexampaperhistory'),
    path('latestlearnerpapers/', contennt_views.FetchLatestLearnerPapersViewSet.as_view(),
         name='latestlearnerpapers'),
    path('overalllatestlearnerpapers/', contennt_views.FetchOverallLatestLearnerPapersViewSet.as_view(),
         name='overalllatestlearnerpapers'),
    path('sharedbymepapers/', contennt_views.SharedByMePapersViewSet.as_view(),
         name='sharedbymepapers'),
    path('sharedtomepapers/', contennt_views.SharedToMePapersViewSet.as_view(),
         name='sharedtomepapers'),
    path('checksharedpaperacceptance/<pk>/', contennt_views.CheckSharedpaperStatusViewSet.as_view(),
         name='checksharedpaperacceptance'),
    path('answerpaperbylearnerpaperids/', contennt_views.FetchAnswerPapersForMultipleLearnerpapersView.as_view(),
         name='answerpaperbylearnerpaperids'),
    path('paperreattempt/', contennt_views.ReattemptPaperLinkingView.as_view(),
         name='paperreattempt'),
    path('savebookmark/', contennt_views.SaveBookMarkView.as_view(),
         name='savebookmarks'),
    path('getbookmarks/', contennt_views.FetchBookmarksViewSetViewSet.as_view(),
         name='getbookmarks'),
    path('deletebookmark/<pk>/', contennt_views.DeleteBookmarkViewSet.as_view(), name='deletebookmark'),
    path('deletetempbookmark/<pk>/', contennt_views.DeleteTemporaryBookmarkViewSet.as_view(), name='deletetempbookmark'), 
    path('getlearnerexamchapters/', contennt_views.LearnerExamChaptersViewSet.as_view(),
         name='getlearnerexamchapters'),
    path('getlearnerexamsubjects/', contennt_views.LearnerExamSubjectsViewSet.as_view(),
         name='getlearnerexamsubjects'),
    path('getlearnerexampracticechapters/', contennt_views.LearnerExamPracticeChaptersViewSet.as_view(),
         name='getlearnerexampracticechapters'),
    path('getlearnerexampracticesubjects/', contennt_views.LearnerExamPracticeSubjectsViewSet.as_view(),
         name='getlearnerexampracticesubjects'),
    path('getlearnerexampaperchapters/', contennt_views.LearnerExamPaperChaptersViewSet.as_view(),
         name='getlearnerexampaperchapters'),
    path('getlearnerexampapersubjects/', contennt_views.LearnerExamPaperSubjectsViewSet.as_view(),
         name='getlearnerexampapersubjects'),
    path('leaderboard/', contennt_views.OverallLeaderboard.as_view(),
         name='leaderboard'),
    path('pausepaper/', contennt_views.PauseLearnePaperViewSet.as_view(),
         name='pausepaper'),
    path('resumepaper/', contennt_views.ResumeLearnePaperViewSet.as_view(),
         name='resumepaper'),
    path('pausegoalpaper/', contennt_views.PauseGoalPaperViewSet.as_view(),
         name='pausegoalpaper'),
    path('resumegoalpaper/', contennt_views.ResumeGoalPaperViewSet.as_view(),
         name='resumegoalpaper'),
    path('assessmentpaper_questions_answers/<int:assessmentpaper_id>/',contennt_views.AssessmentPaperAnswersHistoryView.as_view(), name='assessmentpaper_questions_answers'),
    path('create_query/', contennt_views.CreateUserQueryViewSet.as_view(), name='create_query'),
    path('user_queries/', contennt_views.FetchUserQueriesViewSet.as_view(), name='user_queries'),
    path('batch/', contennt_views.BatchViewSet.as_view(), name='batch'),
    path('batch/<pk>/', contennt_views.EditBatchViewSet.as_view(), name='editbatch'),
    path('deactivatebatch/<pk>/', contennt_views.DeactivateBatchView.as_view(), name='deactivatebatch'),
    path('searchmentorbatch/', contennt_views.SearchMentorBatchViewSetViewSet.as_view(),
         name='searchmentorbatch'),
    path('joinbatch/', contennt_views.JoinBatchViewSet.as_view(), name='joinbatch'),
    path('makementorpaper/', contennt_views.MakeMentorPaperView.as_view(),
         name='makementorpaper'),
    path('temporarybookmark/', contennt_views.TemporaryBookmarkSetViewSet.as_view(), name='temporarybookmark'),
    path('mentorpapers/', contennt_views.FetchMentorPapersViewSet.as_view(),
         name='mentorpapers'),
    path('mentorpapers/<pk>/', contennt_views.FetchMentorPaperByIdViewSet.as_view(),
         name='viewmentorpapers'),
    path('completedmentorpapers/', contennt_views.FetchCompletedMentorPapersViewSet.as_view(),
         name='completedmentorpapers'),
    path('pendingmentorpapers/', contennt_views.FetchPendingMentorPapersViewSet.as_view(),
         name='pendingmentorpapers'),
    path('overmentorpapers/', contennt_views.FetchOverMentorPapersViewSet.as_view(),
         name='overmentorpapers'),
    path('mentorpapersfourinapage/', contennt_views.FetchMentorPapersFourInAPageViewSet.as_view(),
         name='mentorpapersfourinapage'),
    path('completedmentorpapersfourinapage/', contennt_views.FetchCompletedMentorPapersFourInAPageViewSet.as_view(),
         name='completedmentorpapersfourinapage'),
    path('pendingmentorpapersfourinapage/', contennt_views.FetchPendingMentorPapersFourInAPageViewSet.as_view(),
         name='pendingmentorpapersfourinapage'),
    path('overmentorpapersfourinapage/', contennt_views.FetchOverMentorPapersFourInAPageViewSet.as_view(),
         name='overmentorpapersfourinapage'),
    path('learnerbatchhistory/', contennt_views.FetchLearnerBatchHistoryViewSet.as_view(),
         name='learnerbatchhistory'),
    path('report_question/', contennt_views.ReportQuestionViewSet.as_view(), name='report_question'),
    path('reported_questions/', contennt_views.FetchReportedQuestionsViewSet.as_view(), name='reported_questions'),
    path('contact_us/', contennt_views.ContactUsViewSet.as_view(), name='contact_us'),
    path('contact_lists/', contennt_views.FetchContactUsViewSet.as_view(), name='contact_lists'),
    path('create_faq/', contennt_views.FAQViewSet.as_view(), name='create_faq'),
    path('fetchfaq/', contennt_views.FetchFAQViewSet.as_view(), name='fetchfaq'),
    path('editfaq/<pk>/', contennt_views.EditFAQViewSetViewSet.as_view(), name='editfaq'),
    path('replacequestion/', contennt_views.ReplaceQuestionInMentorPaperView.as_view(),
         name='replacequestion'),
    path('findreplacementquestion/', contennt_views.FindReplacementQuestionViewSet.as_view(),
         name='findreplacementquestion'),
    path('mentorassessmentpaper_questions/<int:assessmentpaper_id>/',contennt_views.MentorQuestionAssessmentPaperView.as_view(), name='api_mentorassessmentpaper_questions'),
    path('process_mentorpaper_postsubmit/<int:assessmentpaper_id>/',contennt_views.ProcessMentorPaperPostSubmitView.as_view(), name='process_mentorpaper_postsubmit'),
    path('mentorpaperinstructions/', contennt_views.MentorPapersInstructionsViewSet.as_view(),
         name='mentorpaperinstructions'),
    path('mentorlearneranswerpaper/', contennt_views.FetchMentorlearnerAnswerPaperByIdViewSet.as_view(),
         name='mentorlearneranswerpaper'),
    path('post_answer_mentorpaper/', contennt_views.PostAnswerMentorPaperView.as_view(), name='api_post_answer_mentor'),
    path('mentorassessmentpaper_report/<int:assessmentpaper_id>/',contennt_views.MentorAssessmentPaperReportView.as_view(), name='api_mentorassessmentpaper_report'),
    path('savementorpaperbookmark/', contennt_views.SaveMentorPaperBookMarkView.as_view(),
         name='savementorpaperbookmarks'),
    path('temporarybookmarkmentorpaper/', contennt_views.TemporaryBookmarkMentorPaperSetViewSet.as_view(), name='temporarybookmarkmentorpaper'),
    path('pausementorpaper/', contennt_views.PauseLearnerMentorPaperViewSet.as_view(),
         name='pausementorpaper'),
    path('resumementorpaper/', contennt_views.ResumeLearnerMentorPaperViewSet.as_view(),
         name='resumementorpaper'),
    path('removefrombatch/', contennt_views.RemoveAndBlockUserFromBatchView.as_view(),
         name='removefrombatch'),
    path('checkifblockedfrombatch/', contennt_views.CheckIfBlockedViewSet.as_view(),
         name='checkifblockedfrombatch'),
    path('getallmentorpaperanswerpapers/', contennt_views.FetchAllAnswerPapersInTheMentorPaperViewSet.as_view(),
         name='getallmentorpaperanswerpapers'),
    path('blockedusersinbatch/', contennt_views.FetchBlockedUserInBatchViewSet.as_view(),
         name='blockedusersinbatch'),
    path('unblockusersfrombatch/', contennt_views.UnblockUserFromBatchViewSet.as_view(),
         name='unblockusersfrombatch'),
    path('mentorassessmentpaper_allreports/<int:assessmentpaper_id>/',contennt_views.MentorAssessmentPaperAllUserReportView.as_view(), name='api_mentorassessmentpaper_allreports'),
    path('mentorassessment_questionreport/<int:assessmentpaper_id>/',contennt_views.MentorAssessmentQuestionWiseAnalysisReportView.as_view(), name='api_mentorassessment_questionreport'),
    path('mentorassessment_singlequestionreport/<int:assessmentpaper_id>/',contennt_views.MentorAssessmentSingleQuestionAnalysisReportView.as_view(), name='api_mentorassessment_singlequestionreport'),
    path('batchaccuracyreport/', contennt_views.BatchAccuracyReportView.as_view(),
         name='batchaccuracyreport'),
    path('batchleaderboard/', contennt_views.BatchWiseLeaderboard.as_view(),
         name='batchleaderboard'),
    path('cumulativebatchleaderboard/', contennt_views.CumulativeBatchWiseLeaderboard.as_view(),
         name='cumulativebatchleaderboard'),
    path('mentorpaper_questions_answers/<int:assessmentpaper_id>/',contennt_views.MentorPaperAnswersHistoryView.as_view(), name='mentorpaper_questions_answers'),
    path('mentorpaper_student_stats/<int:assessmentpaper_id>/',contennt_views.MentorPaperStudentStatsView.as_view(), name='mentorpaper_student_stats'),
    path('updateremarks/', contennt_views.UpdatePaperRemarkForUserView.as_view(),
         name='updateremarks'),
    path('fetchuseranswer/', contennt_views.FetchQuestionWiseUserAnswerInLearnerpaperAnswerViewSet.as_view(),
         name='fetchuseranswer'),
    path('fetchuseranswerfrommentorpaper/', contennt_views.FetchQuestionWiseUserAnswerInMentorpaperAnswerViewSet.as_view(),
         name='fetchuseranswerfrommentorpaper'),
    path('updatemockpaperdetails/', contennt_views.SetMockPaperParametersExamWiseViewSet.as_view(),
         name='updatemockpaperdetails'),
     path('deletemockpaperdetails/', contennt_views.DeleteMockPaperParametersExamWiseViewSet.as_view(),
         name='deletemockpaperdetails'),
     path('viewmockpaperdetails/', contennt_views.ViewMockExamDetailsWithoutChapterViewSet.as_view(),
         name='viewmockpaperdetails'),
    path('getmockpaperdetails/', contennt_views.FetchMockExamDetailsViewSet.as_view(),
         name='getmockpaperdetails'),
    path('getmockpapersubjectdetails/', contennt_views.FetchMockSubjectDetailsViewSet.as_view(),
         name='getmockpapersubjectdetails'),
    path('getmockpapersubjectquestypedetails/', contennt_views.FetchMockSubjectQuestionTypeDetailsViewSet.as_view(),
         name='getmockpapersubjectquestypedetails'),
    path('generatemockpaper/', contennt_views.GenerateMockPaperForExamView.as_view(),
         name='generatemockpaper'),
    path('deletetemporaryreplacementquestions/', contennt_views.DeleteMentorPaperTempQuesReplaceViewSet.as_view(),
         name='deletetemporaryreplacementquestions'),
    path('student_batch_paper_count_stats/<int:batch_id>/',contennt_views.BatchStudentPaperCountView.as_view(), name='student_batch_paper_count_stats'),
    path('deletesubjectiveimage/<pk>/', contennt_views.DeleteSubjectiveImageViewSet.as_view(), name='deletesubjectiveimage'),
    path('searchquestionbyidentifier/', contennt_views.SearchQuestionByIdentifierSetViewSet.as_view(),
         name='searchquestionbyidentifier'),
    path('fetchlastquestion/', contennt_views.FetchLastestQuestionViewSet.as_view(),
         name='fetchlastquestion'),
    path('add_remove_ftag_from_question/',
         contennt_views.AddRemoveFTagFromQuestion.as_view(), name='add_remove_ftag_from_question'),
    path('create_banner/', contennt_views.BannerImagesViewSet.as_view(), name='create_banner'),
    path('fetchbanners/', contennt_views.FetchBannerImagesViewSet.as_view(), name='fetchbanners'),
    path('editbanner/<pk>/', contennt_views.EditBannerViewSetViewSet.as_view(), name='editbanner'),
    path('student_practice_chapter_data/<int:exam>/',contennt_views.StudentPracticeChapterDataView.as_view(), name='student_practice_chapter_data'),
    path('findmentorpracticequestions/', contennt_views.FindPracticeChapterQuestionsViewSet.as_view(),
         name='findmentorpracticequestions'),
    path('findmentoractualpaperquestions/', contennt_views.FindPaperChapterQuestionsViewSet.as_view(),
         name='findmentoractualpaperquestions'),
    path('findmentortemppracticequestions/<pk>/', contennt_views.FetchTemporaryPracticeQuestionsViewSet.as_view(),
         name='findmentortemppracticequestions'),
    path('findmentortempactualpaperquestions/<pk>/', contennt_views.FetchTemporaryActualPaperQuestionsViewSet.as_view(),
         name='findmentortempactualpaperquestions'),
    path('findpracticereplacementquestion/', contennt_views.FindReplacementQuestionPracticeViewSet.as_view(),
         name='findpracticereplacementquestion'),
    path('findpapereplacementquestion/', contennt_views.FindReplacementQuestionPaperViewSet.as_view(),
         name='findpapereplacementquestion'),
    path('replacepracticequestion/', contennt_views.ReplaceQuestionInMentorPracticeTempObjView.as_view(),
         name='replacepracticequestion'),
    path('replaceactualpaperequestion/', contennt_views.ReplaceQuestionInMentorActualPaperTempObjView.as_view(),
         name='replaceactualpaperequestion'),
    path('makementorpractice/', contennt_views.MakeMentorPracticePaperView.as_view(),
         name='makementorpractice'),
    path('makementoractualpaper/', contennt_views.MakeMentorActualPaperView.as_view(),
         name='makementoractualpaper'),
    path('learnerexamgoals/', contennt_views.LearnerExamGoalSViewSet.as_view(),
         name='learnerexamgoals'),
    path('creategoalassessment/', contennt_views.CreateExamGoalSelfAssessmentView.as_view(),
         name='creategoalassessment'),
    path('fetchgoalassessmentpaper/<pk>/', contennt_views.FetchSelfAssessAnswerPaperViewSet.as_view(),
         name='fetchgoalassessmentpaper'),
    path('self_assessmentpaper_questions/<int:assessmentpaper_id>/',contennt_views.ExamAssessmentPaperView.as_view(), name='api_self_assessmentpaper_questions'),
    path('post_self_assess_answer/', contennt_views.PostSelfAssessAnswerView.as_view(), name='api_post_self_assess_answer'),
    path('fetchgoalexamquestions/', contennt_views.FetchGoalExamQuestionsView.as_view(),
         name='fetchgoalexamquestions'),
    path('learnerexamgoals/<pk>/', contennt_views.EditLearnerGoalViewSet.as_view(),
         name='editlearnerexamgoals'),
    path('fetchgoalpaper/', contennt_views.FetchExamGoalSelfAssessPaperSViewSet.as_view(),
         name='fetchgoalpaper'),
    path('synctag/', contennt_views.SyncChapterMasterFtagView.as_view(),
         name='synctag'),
    path('fetchquestionschapterwise/', contennt_views.FetchQuestionsByChapterMasterFTagViewSet.as_view(),
         name='fetchquestionschaptermastertagwise'),
    path('toptenexams/', contennt_views.TopTenExamsLeaderboard.as_view(),
         name='toptenexams'),
    path('fetchgoalpathassessmentques/', contennt_views.LearnerGoalPathFetchQuestionsViewSet.as_view(),
         name='fetchgoalpathassessmentques'),
    path('activate_deactivate_question/',
         contennt_views.ActivateDeactivateQuestion.as_view(), name='activate_deactivate_question'),
    path('questionscounttypemastertagwise/', contennt_views.QuestionCountByTypeAndChapterMasterFTagViewSet.as_view(),
         name='questionscounttypemastertagwise'),
    path('syncmastertagbytag/', contennt_views.SyncMasterFtagByParticularTagView.as_view(),
         name='syncmastertagbytag'),
    path('deletementorpapertempbookmark/<pk>/', contennt_views.DeleteMentorPaperTemporaryBookmarkViewSet.as_view(), name='deletementorpapertempbookmark'), 
    path('instituteclassroom/', contennt_views.InstituteClassRoomViewSet.as_view(),
         name='instituteclassroom'),
    path('instituteclassroom/<pk>/', contennt_views.InstituteClassRoomByIdViewSet.as_view(),
         name='viewinstituteclassroom'),
    path('instituteroombatches/', contennt_views.FetchRoomBatchesViewSet.as_view(),
         name='instituteroombatches'),
    path('createclassroombatch/', contennt_views.CreateClassRoomBatchView.as_view(),
         name='createclassroombatch'),
    path('userclassroom/', contennt_views.LinkUserClassRoomViewSet.as_view(),
         name='userclassroom'),
    path('classroomstudents/', contennt_views.FetchStudentsInRoomViewSet.as_view(),
         name='classroomstudents'),
    path('addstudenttoclassroom/', contennt_views.AddStudentToRoomView.as_view(),
         name='addstudenttoclassroom'),
    path('learnergoalpathcreate/', contennt_views.LearnerGoalPathCreateLearChaptersViewSet.as_view(),
         name='learnergoalpathcreate'),
    path('fetchlearnergoalpaths/', contennt_views.FetchGoalPathsViewSet.as_view(),
         name='fetchlearnergoalpaths'),
    path('fetchpathlearnchapters/', contennt_views.FetchPathLearnChaptersViewSet.as_view(),
         name='fetchpathlearnchapters'),
    path('fetchpathlearnchapterhints/', contennt_views.FetchPathLearnChapterHintViewSet.as_view(),
         name='fetchpathlearnchapterhints'),
    path('fetchpathrevisechapters/', contennt_views.FetchPathReviseChaptersViewSet.as_view(),
         name='fetchpathlearnchapters'),
    path('fetchpathrevisechapterhints/', contennt_views.FetchPathReviseChapterHintViewSet.as_view(),
         name='fetchpathrevisechapterhints'),
    path('updatelearnchapterhints/', contennt_views.UpdatePathLearnChapterHintViewSet.as_view(),
         name='updatelearnchapterhints'),
    path('updaterevisechapterhints/', contennt_views.UpdatePathReviseChapterHintViewSet.as_view(),
         name='updaterevisechapterhints'),
    path('bulkaddstudentsinroom/', contennt_views.BulkAddStudentsInClassRoom.as_view(), 
         name='bulkaddstudentsinroom'),
    path('removelanguagecontent/', contennt_views.RemoveLanguageContentFromQuestion.as_view(), name='removelanguagecontent'),
    path('skipgoalassessment/', contennt_views.SetGoalAssessmentSkipped.as_view(), name='skipgoalassessment'),
    path('pregoalassessmentpaper_questions_answers/<int:assessmentpaper_id>/',contennt_views.PreGoalPaperAnswersHistoryView.as_view(), name='pregoalassessmentpaper_questions_answers'),
    path('create_mentorfaq/', contennt_views.MentorFAQViewSet.as_view(), name='create_mentorfaq'),
    path('fetchmentorfaq/', contennt_views.FetchMentorFAQViewSet.as_view(), name='fetchmentorfaq'),
    path('editmentorfaq/<pk>/', contennt_views.EditMentorFAQViewSetViewSet.as_view(), name='editmentorfaq'),
    path('fetchroompendingstudentrequest/', contennt_views.FetchStudentInstituteChangeInvitationViewSet.as_view(),
         name='fetchroompendingstudentrequest'),
    path('approveinstitutechangerequest/', contennt_views.ApproveInstituteRoomRequestView.as_view(), name='approveinstitutechangerequest'),
    path('fetchstudentincominginstitutechangerequest/', contennt_views.FetchStudentIncomingInstituteChangeRequestViewSet.as_view(),
         name='fetchstudentincominginstitutechangerequest'),
    path('checkforfirstpathcreation/', contennt_views.CheckForFirstPathCreationViewSet.as_view(), name='checkforfirstpathcreation'),
    path('checkforsubsequentpathcreation/', contennt_views.CheckForSubsequentPathCreationViewSet.as_view(), name='checkforsubsequentpathcreation'),
    path('userqueryreply/', contennt_views.UserQueryReplyForUserView.as_view(), name='userqueryreply'),
    path('userreportedquestionreply/', contennt_views.UserReportedQuestionReplyForUserView.as_view(), name='userreportedquestionreply'),
    path('learnergoalpercentage/', contennt_views.LearnerGoalPercentageViewSet.as_view(), name='learnergoalpercentage'),
    path('learnergoalpathpercentage/', contennt_views.LearnerGoalPathPercentageViewSet.as_view(), name='learnergoalpathpercentage'),
    path('examalllearnergoalspercentageupdate/', contennt_views.ExamAllLearnerGoalsPercentageViewSet.as_view(), name='examalllearnergoalspercentageupdate'),
    path('updatepathassessment/', contennt_views.LearnerGoalPathUpdateWithAssessmentViewSet.as_view(), name='updatepathassessment'),
    path('deactivatementorallbatches/', contennt_views.DeactivateAllBatchesView.as_view(), name='deactivatementorallbatches'),
    path('activatebatch/<pk>/', contennt_views.ActivateBatchView.as_view(), name='activatebatch'),
    path('postqueryquestions/', contennt_views.PostQuerySuggestiveQuestionsViewSet.as_view(), name='postqueryquestions'),
    path('postqueryquestions/<pk>/', contennt_views.EditPostQuerySuggestiveQuestionViewSet.as_view(), name='editpostqueryquestions'),
    path('savementorbookmark/', contennt_views.SaveMentorBookMarkView.as_view(),
         name='savementorbookmark'),
    path('getmentorbookmarks/', contennt_views.FetchMentorBookmarksViewSetViewSet.as_view(),
         name='getmentorbookmarks'),
    path('deletementorbookmark/<pk>/', contennt_views.DeleteMentorBookmarkViewSet.as_view(), name='deletementorbookmark'),
    path('getmentorexamchapters/', contennt_views.MentorExamChaptersViewSet.as_view(),
         name='getmentorexamchapters'),
    path('getmentorexamsubjects/', contennt_views.MentorExamSubjectsViewSet.as_view(),
         name='getmentorexamsubjects'),
    path('fetchroomscountinschool/', contennt_views.FetchTotalClassRoomsInInstituteViewSet.as_view(),
         name='fetchroomscountinschool'),
    path('updateroomteacher/', contennt_views.UpdateInstituteRoomTeacherView.as_view(),
         name='updateroomteacher'),
    path('mentorpapersforrelativegrowth/', contennt_views.FetchActualMentorPapersRelativeGrowthViewSet.as_view(),
         name='mentorpapersforrelativegrowth'),
    path('deactivatelearnerexamgoal/', contennt_views.DeactivateGoal.as_view(),
         name='deactivatelearnerexamgoal'),
    path('path/<pk>/', contennt_views.FetchPathByIdPaperViewSet.as_view(),
         name='path'),
]
