# Generated by Django 2.1.5 on 2022-10-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmp_school', '0002_auto_20220930_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolseasson',
            name='seassion_name',
        ),
    ]
