# Generated by Django 2.1.5 on 2022-10-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmp_school', '0003_remove_schoolseasson_seassion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolseasson',
            name='seassion_name',
            field=models.CharField(choices=[('1', '2020-2021'), ('2', '2021-2022'), ('3', '2022-2023'), ('4', '2023-2024'), ('5', '2024-2025')], default='1', max_length=50),
        ),
    ]
