# Generated by Django 2.1.5 on 2022-10-20 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userseasson'),
        ('content', '0164_auto_20221013_1055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mmp_school', '0005_auto_20221013_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchThird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unique_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserClass')),
            ],
        ),
        migrations.RemoveField(
            model_name='batch',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='institute_room',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='students',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='branchschool',
            name='school',
        ),
        migrations.RemoveField(
            model_name='branchschool',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instituteclassroom',
            name='blocked_students',
        ),
        migrations.RemoveField(
            model_name='instituteclassroom',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='instituteclassroom',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='instituteclassroom',
            name='room_teacher',
        ),
        migrations.RemoveField(
            model_name='learnerbatches',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='learnerbatches',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schoolseasson',
            name='schoolbranch',
        ),
        migrations.RemoveField(
            model_name='studentinstitutechangeinvitation',
            name='inviting_institute_room',
        ),
        migrations.RemoveField(
            model_name='studentinstitutechangeinvitation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userclassroom',
            name='institute_rooms',
        ),
        migrations.RemoveField(
            model_name='userclassroom',
            name='user',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='BranchSchool',
        ),
        migrations.DeleteModel(
            name='InstituteClassRoom',
        ),
        migrations.DeleteModel(
            name='LearnerBatches',
        ),
        migrations.DeleteModel(
            name='SchoolSeasson',
        ),
        migrations.DeleteModel(
            name='StudentInstituteChangeInvitation',
        ),
        migrations.DeleteModel(
            name='UserClassRoom',
        ),
        migrations.AddField(
            model_name='batchthird',
            name='institute_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.InstituteClassRoom'),
        ),
        migrations.AddField(
            model_name='batchthird',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='thirdstudents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchthird',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='teacher_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
