# Generated by Django 2.1.5 on 2022-10-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmp_school', '0006_auto_20221020_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchthird',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
