# Generated by Django 2.1.5 on 2022-11-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmp_school', '0007_auto_20221020_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeysForVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyvalues', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
