# Generated by Django 2.1.5 on 2023-01-02 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mmp_school', '0008_apikeysforverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communication',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
