# Generated by Django 2.1.5 on 2023-04-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmp_school', '0013_auto_20230225_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloomlevelvalues',
            name='total_question',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
