# Generated by Django 2.1.5 on 2021-05-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('node', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=100)),
                ('question_text', models.CharField(blank=True, max_length=100)),
                ('domain', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.ExamDomain')),
                ('journey_nodes', models.ManyToManyField(blank=True, to='courses.JourneyNode')),
                ('linked_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Exam')),
                ('successive_nodes', models.ManyToManyField(blank=True, related_name='_pathnodes_successive_nodes_+', to='courses.PathNodes')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
