# Generated by Django 2.1.5 on 2021-05-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210525_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathnodes',
            name='question_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
