# Generated by Django 2.1.5 on 2021-05-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210525_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathnodes',
            name='successive_nodes',
            field=models.ManyToManyField(blank=True, null=True, related_name='_pathnodes_successive_nodes_+', to='courses.PathNodes'),
        ),
    ]
