# Generated by Django 2.1.5 on 2021-05-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210525_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathnodes',
            name='journey_nodes',
            field=models.ManyToManyField(blank=True, null=True, to='courses.JourneyNode'),
        ),
    ]
