# Generated by Django 2.1.5 on 2021-05-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210526_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdomain',
            name='journeys',
        ),
    ]
