# Generated by Django 2.1.5 on 2021-05-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_examdomain_exams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdomain',
            name='domain_questions',
        ),
    ]
