# Generated by Django 2.1.5 on 2021-05-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_examdomain_domain_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainpathquestions',
            name='options',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='domain_questions',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='questionoptions',
            name='linked_exam',
        ),
        migrations.DeleteModel(
            name='DomainPathQuestions',
        ),
        migrations.DeleteModel(
            name='Journey',
        ),
        migrations.DeleteModel(
            name='QuestionOptions',
        ),
    ]
