# Generated by Django 2.1.5 on 2021-05-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210526_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamLabel',
            new_name='ExamLevel',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='label',
            new_name='level',
        ),
    ]
