# Generated by Django 2.1.5 on 2021-05-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210526_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathnodes',
            name='successive_nodes',
            field=models.ManyToManyField(blank=True, null=True, to='courses.PathNodes'),
        ),
    ]
