# Generated by Django 2.1.5 on 2021-05-28 09:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_exammakepathquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammakepathquestions',
            name='answer',
        ),
        migrations.AddField(
            model_name='exammakepathquestions',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='content'),
        ),
    ]
