# Generated by Django 2.1.5 on 2021-05-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210528_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdomain',
            name='exams',
            field=models.ManyToManyField(blank=True, to='courses.Exam'),
        ),
        migrations.AlterField(
            model_name='pathnodes',
            name='journey_nodes',
            field=models.ManyToManyField(blank=True, to='courses.JourneyNode'),
        ),
        migrations.AlterField(
            model_name='pathnodes',
            name='successive_nodes',
            field=models.ManyToManyField(blank=True, to='courses.PathNodes'),
        ),
    ]
