# Generated by Django 2.1.5 on 2021-05-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210529_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Exam'),
        ),
    ]
