# Generated by Django 2.1.5 on 2021-05-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_chapter_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='exam',
        ),
    ]
