# Generated by Django 2.1.5 on 2021-05-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_question_linked_topics'),
        ('courses', '0019_auto_20210529_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='tags',
            field=models.ManyToManyField(blank=True, to='content.QuestionTag'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Topic'),
        ),
    ]
