# Generated by Django 2.1.5 on 2021-05-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20210531_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='tags',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='topics',
            field=models.ManyToManyField(blank=True, to='courses.Topic'),
        ),
    ]
