# Generated by Django 2.1.5 on 2021-06-07 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_learnerexams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerexams',
            name='exam',
        ),
        migrations.AddField(
            model_name='learnerexams',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Exam'),
        ),
    ]
