# Generated by Django 2.1.5 on 2021-06-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20210607_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerexams',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.ExamDomain'),
        ),
    ]
