# Generated by Django 2.1.5 on 2021-06-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_questiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
