# Generated by Django 2.1.5 on 2021-06-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_examaveragemarksperquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examaveragemarksperquestion',
            old_name='marks',
            new_name='time',
        ),
    ]
