# Generated by Django 2.1.5 on 2021-06-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20210612_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='type_of_question',
            field=models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choice'), ('fillup', 'Fill In The Blanks'), ('subjective', 'Subjective type'), ('numerical', 'Numerical'), ('assertion', 'Assertion'), ('boolean', 'True False')], max_length=50),
        ),
    ]
