# Generated by Django 2.1.5 on 2021-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_auto_20210612_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerexams',
            name='domain',
        ),
        migrations.AddField(
            model_name='questiontype',
            name='negative_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='type_of_question',
            field=models.CharField(blank=True, choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choice'), ('fillup', 'Fill In The Blanks'), ('subjective', 'Subjective type'), ('numerical', 'Numerical'), ('assertion', 'Assertion'), ('boolean', 'True False')], max_length=50, null=True),
        ),
    ]
