# Generated by Django 2.1.5 on 2021-06-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20210612_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='type_of_question',
            field=models.CharField(blank=True, choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choice'), ('fillup', 'Fill In The Blanks'), ('subjective', 'Subjective type'), ('numerical', 'Numerical'), ('assertion', 'Assertion'), ('boolean', 'True False'), ('fillup_option', 'Fill With Option')], max_length=50, null=True),
        ),
    ]
