# Generated by Django 2.1.5 on 2021-06-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_auto_20210623_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainannouncement',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='domainannouncement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
