# Generated by Django 2.1.5 on 2021-07-01 05:21

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_auto_20210626_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSuggestedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to=courses.models.course_image_upload_to)),
                ('about', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publication', models.CharField(blank=True, max_length=200, null=True)),
                ('amazon_link', models.CharField(blank=True, max_length=700, null=True)),
                ('flipkart_link', models.CharField(blank=True, max_length=700, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Exam')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Subject')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
