# Generated by Django 2.1.5 on 2021-07-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_examsuggestedbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='average_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='average_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='excellent_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='excellent_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='poor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
