# Generated by Django 2.1.5 on 2021-07-02 11:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_examsuggestedbooks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsuggestedbooks',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='about'),
        ),
    ]
