# Generated by Django 2.1.5 on 2021-07-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_exampreviousyearsdpcs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamPreviousYearsDpcs',
            new_name='ExamPreviousYearsPapers',
        ),
    ]
