# Generated by Django 2.1.5 on 2021-07-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_auto_20210716_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampreviousyearspapers',
            name='subject',
        ),
    ]
