# Generated by Django 2.1.5 on 2021-07-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_remove_exampreviousyearspapers_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerexams',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
