# Generated by Django 2.1.5 on 2021-07-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_mentorexams'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterHints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='hints',
            field=models.ManyToManyField(blank=True, to='courses.ChapterHints'),
        ),
    ]
