# Generated by Django 2.1.5 on 2021-07-28 09:33

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_auto_20210728_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsuggestedbooks',
            name='file',
            field=models.FileField(blank=True, upload_to=courses.models.course_image_upload_to),
        ),
    ]
