# Generated by Django 2.1.5 on 2021-08-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_auto_20210830_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='negative_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
