# Generated by Django 2.1.5 on 2021-09-01 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_auto_20210830_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTotalStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_students', models.IntegerField(blank=True, default=0, null=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Exam')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
