# Generated by Django 2.1.5 on 2021-09-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_examtotalstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsuggestedbooks',
            name='subject',
        ),
        migrations.AddField(
            model_name='examsuggestedbooks',
            name='subject',
            field=models.ManyToManyField(blank=True, to='courses.Subject'),
        ),
    ]
