# Generated by Django 2.1.5 on 2021-09-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_auto_20210915_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammakepathquestions',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
