# Generated by Django 2.1.5 on 2021-10-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_exammakepathquestions_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_order',
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
