# Generated by Django 2.1.5 on 2021-10-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_examstudentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdomain',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
