# Generated by Django 2.1.5 on 2021-10-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_examdomain_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcategory',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
