# Generated by Django 2.1.5 on 2021-10-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_examcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
