# Generated by Django 2.1.5 on 2021-10-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_subject_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='show',
        ),
        migrations.AddField(
            model_name='chapter',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
