# Generated by Django 2.1.5 on 2021-10-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_auto_20211014_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
