# Generated by Django 2.1.5 on 2021-11-05 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_subject_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.Subject'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='courses.Topic'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='average_high',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='average_low',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='excellent_high',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='excellent_low',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='poor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
