# Generated by Django 2.1.5 on 2021-12-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_auto_20211206_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfassessmcqoptions',
            name='correct',
        ),
    ]
