# Generated by Django 2.1.5 on 2021-12-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0065_learnerexamgoals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerexamgoals',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='learnerexamgoals',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='learnerexamgoals',
            name='user',
        ),
        migrations.DeleteModel(
            name='LearnerExamGoals',
        ),
    ]
