# Generated by Django 2.1.5 on 2021-12-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_exam_allow_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassessquestion',
            name='type_of_question',
            field=models.CharField(blank=True, choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choice'), ('fillup', 'Fill In The Blanks')], max_length=50, null=True),
        ),
    ]
