# Generated by Django 2.1.5 on 2021-12-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0068_selfassessquestion_type_of_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterHintConcepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='chapterhints',
            name='bloom_level',
            field=models.CharField(blank=True, choices=[('memory', 'Memory Based'), ('conceptual', 'Conceptual'), ('application', 'Application')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chapterhints',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapterhints',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapterhints',
            name='learning_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapterhints',
            name='practice_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapterhints',
            name='revision_importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapterhints',
            name='concepts',
            field=models.ManyToManyField(blank=True, to='courses.ChapterHintConcepts'),
        ),
    ]
