# Generated by Django 2.1.5 on 2021-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0069_auto_20211227_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterhints',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
