# Generated by Django 2.1.5 on 2021-12-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0070_chapterhints_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloomLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='chapterhints',
            name='bloom_level',
        ),
        migrations.AddField(
            model_name='chapterhints',
            name='bloom_level',
            field=models.ManyToManyField(blank=True, to='courses.BloomLevel'),
        ),
    ]
