# Generated by Django 2.1.5 on 2022-01-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0071_auto_20211229_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdomain',
            name='show_home',
            field=models.BooleanField(default=False),
        ),
    ]
