# Generated by Django 2.1.5 on 2022-01-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0072_examdomain_show_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassessquestion',
            name='is_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selfassessquestion',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
