# Generated by Django 2.1.5 on 2022-01-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0073_auto_20220131_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfassessquestion',
            old_name='is_number',
            new_name='is_numeric',
        ),
    ]
