# Generated by Django 2.1.5 on 2022-03-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0076_domainannouncement_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssessExamQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='courses.Exam')),
            ],
        ),
        migrations.RemoveField(
            model_name='selfassessquestion',
            name='exam',
        ),
        migrations.AddField(
            model_name='selfassessexamquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='courses.SelfAssessQuestion'),
        ),
    ]
