# Generated by Django 2.1.5 on 2022-04-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0077_auto_20220309_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassessexamquestions',
            name='is_compulsory',
            field=models.BooleanField(default=True),
        ),
    ]
