# Generated by Django 2.1.5 on 2022-05-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0160_instituteclassroom_room_teacher'),
        ('courses', '0078_selfassessexamquestions_is_compulsory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorexams',
            name='batches',
            field=models.ManyToManyField(blank=True, to='content.Batch'),
        ),
    ]
