# Generated by Django 2.1.5 on 2022-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0079_mentorexams_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathnodes',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
