# Generated by Django 2.1.5 on 2022-06-18 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0081_examdomain_consider_node_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('description', models.TextField(null=True)),
                ('avg_rating', models.FloatField(default=5)),
                ('total_ratings', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='UserRatingOnChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(help_text='rating given by user')),
                ('chapter_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ChapterVideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userratingonchapter',
            unique_together={('chapter_video', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='chaptervideo',
            unique_together={('chapter', 'url', 'is_active')},
        ),
    ]
