# Generated by Django 2.1.5 on 2022-09-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0082_auto_20220618_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptervideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
