# Generated by Django 2.1.5 on 2021-05-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='linked_topics',
        ),
    ]
