# Generated by Django 2.1.5 on 2021-05-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20210531_1347'),
        ('content', '0002_remove_question_linked_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='linked_topics',
            field=models.ManyToManyField(blank=True, to='courses.Topic'),
        ),
    ]
