# Generated by Django 2.1.5 on 2021-06-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
    ]
