# Generated by Django 2.1.5 on 2021-06-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210604_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='content.QuestionTag'),
        ),
    ]
