# Generated by Django 2.1.5 on 2021-06-07 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_learnerexams_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0008_auto_20210605_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_practice_time', models.IntegerField(default=0)),
                ('total_paper_time', models.IntegerField(default=0)),
                ('learner_exam', models.ManyToManyField(blank=True, null=True, to='courses.LearnerExams')),
                ('questions', models.ManyToManyField(blank=True, to='content.Question')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
