# Generated by Django 2.1.5 on 2021-06-08 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_learnerexams_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0009_learnerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.LearnerExams')),
                ('questions', models.ManyToManyField(blank=True, null=True, to='content.Question')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
