# Generated by Django 2.1.5 on 2021-06-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_learnerpapers'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpapers',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerpapers',
            name='paper_type',
            field=models.CharField(choices=[('practice', 'Practice'), ('paper', 'Paper')], default=0, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnerpapers',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
