# Generated by Django 2.1.5 on 2021-06-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_learnerhistory_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpapers',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
