# Generated by Django 2.1.5 on 2021-06-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_learnerpapers_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_of_question',
            field=models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choice'), ('fillup', 'Fill In The Blanks'), ('subjective', 'Subjective type'), ('numerical', 'Numerical'), ('assertion', 'Assertion')], max_length=24),
        ),
    ]
