# Generated by Django 2.1.5 on 2021-06-11 05:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20210611_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpapers',
            name='instruction',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='instruction'),
        ),
    ]
