# Generated by Django 2.1.5 on 2021-06-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_learnerpapers_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperInstructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instruction', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='learnerpapers',
            name='instruction',
        ),
        migrations.AddField(
            model_name='paperinstructions',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.LearnerPapers'),
        ),
    ]
