# Generated by Django 2.1.5 on 2021-06-16 08:28

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0018_auto_20210612_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date and Time of the qp')),
                ('paper_complete', models.BooleanField(default=False)),
                ('attempt_order', models.IntegerField(default=0, verbose_name='Number of Attempt paper')),
                ('time_taken', models.IntegerField(default=0, verbose_name='Number of minutes to finish paper')),
                ('attempted_date', models.DateField(blank=True, null=True)),
                ('question_order', models.TextField(blank=True, default='')),
                ('assessment_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.LearnerPapers')),
                ('question_answered', models.ManyToManyField(blank=True, related_name='question_answered', to='content.Question')),
                ('question_markforreview', models.ManyToManyField(blank=True, related_name='question_markforreview', to='content.Question')),
                ('question_save_markforreview', models.ManyToManyField(blank=True, related_name='question_save_markforreview', to='content.Question')),
                ('question_unanswered', models.ManyToManyField(blank=True, related_name='question_unanswered', to='content.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_order', models.IntegerField(default=0)),
                ('timespent', models.IntegerField(blank=True, null=True)),
                ('type_of_answer', models.CharField(max_length=24)),
                ('user_string_answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='text')),
                ('user_subjective_answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='user subjective answer')),
                ('teacher_subjective_comment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='teacher subjective comment')),
                ('status', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('answer_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.AnswerPaper')),
                ('correct_mcq_answer', models.ManyToManyField(blank=True, related_name='correct_mcq_answer', to='content.McqTestCase')),
                ('correct_string_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_string_answer', to='content.StringTestCase')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_mcq_answer', models.ManyToManyField(blank=True, related_name='user_mcq_answer', to='content.McqTestCase')),
            ],
        ),
    ]
