# Generated by Django 2.1.5 on 2021-06-18 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20210618_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='correct_boolean_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_boolean_answer', to='content.TrueFalseSolution'),
        ),
    ]
