# Generated by Django 2.1.5 on 2021-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20210612_1524'),
        ('content', '0022_useranswer_user_boolean_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpapers',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Subject'),
        ),
    ]
