# Generated by Django 2.1.5 on 2021-06-24 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0034_auto_20210623_2052'),
        ('content', '0023_learnerpapers_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerExamHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_practice_time', models.IntegerField(default=0)),
                ('total_paper_time', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Exam')),
                ('papers', models.ManyToManyField(blank=True, null=True, to='content.LearnerPapers')),
                ('questions', models.ManyToManyField(blank=True, to='content.Question')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
