# Generated by Django 2.1.5 on 2021-06-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_learnerexamhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpapers',
            name='show_marks',
            field=models.BooleanField(default=True),
        ),
    ]
