# Generated by Django 2.1.5 on 2021-06-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_learnerpapers_show_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnerpapers',
            old_name='show_marks',
            new_name='show_time',
        ),
    ]
