# Generated by Django 2.1.5 on 2021-06-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_question_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='time',
            new_name='ideal_time',
        ),
    ]
