# Generated by Django 2.1.5 on 2021-07-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20210630_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerpapers',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmarks', to='content.LearnerBookmarks'),
        ),
    ]
