# Generated by Django 2.1.5 on 2021-07-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20210701_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnerbookmarks',
            old_name='exam',
            new_name='learner_exam',
        ),
    ]
