# Generated by Django 2.1.5 on 2021-07-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_questioncontent_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpapers',
            name='actual_paper_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerpapers',
            name='reattempt_papers',
            field=models.ManyToManyField(blank=True, null=True, to='content.LearnerPapers'),
        ),
        migrations.AddField(
            model_name='learnerpapers',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
