# Generated by Django 2.1.5 on 2021-07-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_learnerexamchapters_learnerexamsubjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerexamchapters',
            name='total_bookmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexamsubjects',
            name='total_bookmarks',
            field=models.IntegerField(default=0),
        ),
    ]
