# Generated by Django 2.1.5 on 2021-07-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_learnerexampaperchapters_learnerexampapersubjects_learnerexampracticechapters_learnerexampracticesub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerexampaperchapters',
            name='total_bookmarks',
        ),
        migrations.RemoveField(
            model_name='learnerexampapersubjects',
            name='total_bookmarks',
        ),
        migrations.RemoveField(
            model_name='learnerexampracticechapters',
            name='total_bookmarks',
        ),
        migrations.RemoveField(
            model_name='learnerexampracticesubjects',
            name='total_bookmarks',
        ),
    ]
