# Generated by Django 2.1.5 on 2021-07-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_learnerexampaperhistory_learnerexampracticehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerexampaperhistory',
            name='attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampaperhistory',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampaperhistory',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampaperhistory',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampaperhistory',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampaperhistory',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampaperhistory',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampaperhistory',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampracticehistory',
            name='attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampracticehistory',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampracticehistory',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampracticehistory',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampracticehistory',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampracticehistory',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampracticehistory',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampracticehistory',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
