# Generated by Django 2.1.5 on 2021-07-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_auto_20210709_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerexampaperhistory',
            name='skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampracticehistory',
            name='skipped',
            field=models.IntegerField(default=0),
        ),
    ]
