# Generated by Django 2.1.5 on 2021-07-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_auto_20210709_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpaper',
            name='attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
