# Generated by Django 2.1.5 on 2021-07-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_temporarylearnerbookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerpapers',
            name='actual_paper_id',
        ),
        migrations.AddField(
            model_name='learnerpapers',
            name='actual_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_learnerpaper', to='content.LearnerPapers'),
        ),
    ]
