# Generated by Django 2.1.5 on 2021-07-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_auto_20210710_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpapers',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
