# Generated by Django 2.1.5 on 2021-07-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_learnerpapers_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpapers',
            name='remaining_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
