# Generated by Django 2.1.5 on 2021-07-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_learnerpapers_remaining_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpapers',
            name='pause_count',
            field=models.IntegerField(default=0),
        ),
    ]
