# Generated by Django 2.1.5 on 2021-07-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_learnerpapers_pause_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='content.QuestionLanguage'),
        ),
    ]
