# Generated by Django 2.1.5 on 2021-07-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_auto_20210714_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user_boolean_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
