# Generated by Django 2.1.5 on 2021-07-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_auto_20210717_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerpapers',
            name='paper_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learnertotalactualpapers',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learnertotalpracticepapers',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
