# Generated by Django 2.1.5 on 2021-07-19 10:48

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_auto_20210717_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubjectiveAnswerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_subjective_answer_image', models.FileField(blank=True, null=True, upload_to=content.models.user_subjective_answer_image, verbose_name='user subjective answer image')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_subjective_answer_image',
            field=models.FileField(blank=True, null=True, upload_to=content.models.user_subjective_answer_image, verbose_name='user subjective answer image'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_subjective_answer_images',
            field=models.ManyToManyField(blank=True, to='content.UserSubjectiveAnswerImage'),
        ),
    ]
