# Generated by Django 2.1.5 on 2021-07-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0062_mentorpaperinstructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='correct_filloption_answer',
            field=models.ManyToManyField(blank=True, related_name='correct_filloption_answer', to='content.FillUpWithOption'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_filloption_answer',
            field=models.ManyToManyField(blank=True, related_name='user_filloption_answer', to='content.FillUpWithOption'),
        ),
    ]
