# Generated by Django 2.1.5 on 2021-07-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0063_auto_20210722_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='correct_filloption_answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user_filloption_answer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_fillup_option_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fillup_option_answer', to='content.FillUpWithOption'),
        ),
    ]
