# Generated by Django 2.1.5 on 2021-07-26 12:23

import ckeditor_uploader.fields
import content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0064_auto_20210722_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerBatchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_paper_count', models.IntegerField(default=0)),
                ('total_practice_count', models.IntegerField(default=0)),
                ('total_practice_time_taken', models.IntegerField(default=0)),
                ('total_paper_time_taken', models.IntegerField(default=0)),
                ('paper_score', models.IntegerField(default=0)),
                ('total_paper_marks', models.IntegerField(default=0)),
                ('practice_score', models.IntegerField(default=0)),
                ('total_practice_marks', models.IntegerField(default=0)),
                ('paper_percentage', models.IntegerField(default=0)),
                ('practice_percentage', models.IntegerField(default=0)),
                ('total_paper_time', models.IntegerField(default=0)),
                ('total_practice_time', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('attempted', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Batch')),
                ('papers', models.ManyToManyField(blank=True, null=True, to='content.MentorPapers')),
                ('questions', models.ManyToManyField(blank=True, to='content.Question')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAnswerMentorPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_order', models.IntegerField(default=0)),
                ('timespent', models.IntegerField(blank=True, null=True)),
                ('type_of_answer', models.CharField(max_length=24)),
                ('user_string_answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='text')),
                ('user_boolean_answer', models.BooleanField(blank=True, null=True)),
                ('user_subjective_answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='user subjective answer')),
                ('user_subjective_answer_image', models.FileField(blank=True, null=True, upload_to=content.models.user_subjective_answer_image, verbose_name='user subjective answer image')),
                ('teacher_subjective_comment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='teacher subjective comment')),
                ('status', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('answer_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.MentorPaperAnswerPaper')),
                ('correct_boolean_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_boolean_answer_mentor_paper', to='content.TrueFalseSolution')),
                ('correct_fillup_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_fillup_answer_mentor_paper', to='content.FillUpSolution')),
                ('correct_fillup_option_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_fillup_option_answer_mentor_paper', to='content.FillUpWithOption')),
                ('correct_mcq_answer', models.ManyToManyField(blank=True, related_name='correct_mcq_answer_mentor_paper', to='content.McqTestCase')),
                ('correct_string_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_string_answer_mentor_paper', to='content.StringTestCase')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_fillup_option_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fillup_option_answer_mentor_paper', to='content.FillUpWithOption')),
                ('user_mcq_answer', models.ManyToManyField(blank=True, related_name='user_mcq_answer_mentor_paper', to='content.McqTestCase')),
                ('user_subjective_answer_images', models.ManyToManyField(blank=True, to='content.UserSubjectiveAnswerImage')),
            ],
        ),
    ]
