# Generated by Django 2.1.5 on 2021-07-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_learnerbatchhistory_useranswermentorpaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnerbatchhistory',
            old_name='attempted',
            new_name='total_attempted_paper',
        ),
        migrations.RenameField(
            model_name='learnerbatchhistory',
            old_name='correct',
            new_name='total_attempted_practice',
        ),
        migrations.RenameField(
            model_name='learnerbatchhistory',
            old_name='incorrect',
            new_name='total_correct_paper',
        ),
        migrations.RenameField(
            model_name='learnerbatchhistory',
            old_name='skipped',
            new_name='total_correct_practice',
        ),
        migrations.AddField(
            model_name='learnerbatchhistory',
            name='total_incorrect_paper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerbatchhistory',
            name='total_incorrect_practice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerbatchhistory',
            name='total_skipped_paper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerbatchhistory',
            name='total_skipped_practice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentorpaperanswerpaper',
            name='reattempt_papers',
            field=models.ManyToManyField(blank=True, null=True, to='content.MentorPaperAnswerPaper'),
        ),
    ]
