# Generated by Django 2.1.5 on 2021-07-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0066_auto_20210726_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorpapers',
            name='difficulty_level',
            field=models.IntegerField(default=5),
        ),
    ]
