# Generated by Django 2.1.5 on 2021-08-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0069_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportederrorneousquestion',
            name='query',
            field=models.CharField(blank=True, max_length=1100, null=True),
        ),
    ]
