# Generated by Django 2.1.5 on 2021-08-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0071_auto_20210810_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymentorpaperlearnerbookmarks',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.MentorPaperAnswerPaper'),
        ),
    ]
