# Generated by Django 2.1.5 on 2021-08-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0073_learnerblockedbatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorpaperanswerpaper',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
