# Generated by Django 2.1.5 on 2021-08-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0076_mentorpaperanswerpaper_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorpaperanswerpaper',
            old_name='query',
            new_name='remarks',
        ),
    ]
