# Generated by Django 2.1.5 on 2021-08-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0077_auto_20210817_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerhistory',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
