# Generated by Django 2.1.5 on 2021-08-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0078_learnerhistory_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerexamhistory',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
