# Generated by Django 2.1.5 on 2021-08-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_examsuggestedbooks_file'),
        ('content', '0079_learnerexamhistory_total_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockPaperExamDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty_level', models.IntegerField(default=5)),
                ('show_time', models.BooleanField(default=True)),
                ('chapters', models.ManyToManyField(blank=True, to='courses.Chapter')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Exam')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MockPaperSubjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapters', models.ManyToManyField(blank=True, to='courses.Chapter')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Subject')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MockPaperSubjectQuestionTypeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_of_question', models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choice'), ('fillup', 'Fill In The Blanks'), ('subjective', 'Subjective type'), ('numerical', 'Numerical'), ('assertion', 'Assertion'), ('boolean', 'True False'), ('fillup_option', 'Fill With Option')], max_length=24)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Subject')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
