# Generated by Django 2.1.5 on 2021-08-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0080_mockpaperexamdetails_mockpapersubjectdetails_mockpapersubjectquestiontypedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpaper',
            name='unchecked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexamchapters',
            name='unchecked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampaperchapters',
            name='unchecked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampaperhistory',
            name='unchecked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampapersubjects',
            name='unchecked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampracticechapters',
            name='unchecked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampracticehistory',
            name='unchecked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexampracticesubjects',
            name='unchecked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexamsubjects',
            name='unchecked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentorpaperanswerpaper',
            name='unchecked',
            field=models.IntegerField(default=0),
        ),
    ]
