# Generated by Django 2.1.5 on 2021-08-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0081_auto_20210825_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryMentorPaperReplaceQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.MentorPaperAnswerPaper')),
                ('question', models.ManyToManyField(blank=True, to='content.Question')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
