# Generated by Django 2.1.5 on 2021-08-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0082_temporarymentorpaperreplacequestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporarymentorpaperreplacequestions',
            old_name='question',
            new_name='questions',
        ),
        migrations.AlterField(
            model_name='temporarymentorpaperreplacequestions',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.MentorPapers'),
        ),
    ]
