# Generated by Django 2.1.5 on 2021-08-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0083_auto_20210826_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymentorpaperreplacequestions',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='content.Question'),
        ),
    ]
