# Generated by Django 2.1.5 on 2021-09-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0086_auto_20210904_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerbatchhistory',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
