# Generated by Django 2.1.5 on 2021-09-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0087_learnerbatchhistory_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpaper',
            name='attempted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorpaperanswerpaper',
            name='attempted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
