# Generated by Django 2.1.5 on 2021-10-08 06:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0088_auto_20210920_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assigned_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='associated_questions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='associated_questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='author_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='edit_after_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='error_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='faculty_check',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='formatting_needed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='perfetly',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='primary_check',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_info_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='solution_missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tag_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='total_language',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='update_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='waste_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
