# Generated by Django 2.1.5 on 2021-10-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0089_auto_20211008_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockpapersubjectquestiontypedetails',
            name='type_of_question',
            field=models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choice'), ('fillup', 'Fill In The Blanks'), ('subjective', 'Subjective type'), ('numerical', 'Numerical'), ('assertion', 'Assertion'), ('boolean', 'True False'), ('fillup_option', 'Fill With Option'), ('comprehension', 'Comprehension')], max_length=24),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_of_question',
            field=models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choice'), ('fillup', 'Fill In The Blanks'), ('subjective', 'Subjective type'), ('numerical', 'Numerical'), ('assertion', 'Assertion'), ('boolean', 'True False'), ('fillup_option', 'Fill With Option'), ('comprehension', 'Comprehension')], max_length=24),
        ),
    ]
