# Generated by Django 2.1.5 on 2021-10-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0090_auto_20211008_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='associated_questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
