# Generated by Django 2.1.5 on 2021-10-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0091_auto_20211008_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncontent',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
