# Generated by Django 2.1.5 on 2021-11-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0095_batch_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='question',
            index_together={('type_of_question', 'difficulty')},
        ),
    ]
