# Generated by Django 2.1.5 on 2021-11-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_auto_20211105_1143'),
        ('content', '0096_auto_20211113_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerpapers',
            name='chapters',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Chapter'),
        ),
    ]
