# Generated by Django 2.1.5 on 2021-11-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_auto_20211105_1143'),
        ('content', '0097_learnerpapers_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorpapers',
            name='chapters',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Chapter'),
        ),
    ]
