# Generated by Django 2.1.5 on 2021-11-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_auto_20211105_1143'),
        ('content', '0098_mentorpapers_chapters'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryMentorPracticeReplaceQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Batch')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.MentorExams')),
                ('questions', models.ManyToManyField(blank=True, null=True, to='content.Question')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
