# Generated by Django 2.1.5 on 2021-11-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0099_temporarymentorpracticereplacequestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymentorpracticereplacequestions',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Exam'),
        ),
    ]
