# Generated by Django 2.1.5 on 2021-11-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0102_temporarymentorpracticereplacequestions_exam_end_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarymentorpracticereplacequestions',
            name='difficulty_level',
            field=models.IntegerField(default=5),
        ),
    ]
