# Generated by Django 2.1.5 on 2021-12-08 13:47

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_auto_20211207_1307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0105_auto_20211207_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssessExamAnswerPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date and Time of the qp')),
                ('paper_complete', models.BooleanField(default=False)),
                ('total_questions', models.IntegerField(default=0)),
                ('attempted', models.IntegerField(default=0)),
                ('attempted_date', models.DateTimeField(blank=True, null=True)),
                ('question_order', models.TextField(blank=True, default='')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.LearnerExamGoals')),
                ('question_answered', models.ManyToManyField(blank=True, related_name='question_answered', to='courses.SelfAssessQuestion')),
                ('question_unanswered', models.ManyToManyField(blank=True, related_name='question_unanswered', to='courses.SelfAssessQuestion')),
                ('questions', models.ManyToManyField(blank=True, null=True, to='courses.SelfAssessQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelfAssessUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_order', models.IntegerField(default=0)),
                ('type_of_answer', models.CharField(max_length=24)),
                ('teacher_comment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='teacher comment')),
                ('status', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('answer_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.SelfAssessExamAnswerPaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.SelfAssessQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_mcq_answer', models.ManyToManyField(blank=True, related_name='user_mcq_answer', to='courses.SelfAssessMcqOptions')),
            ],
        ),
    ]
