# Generated by Django 2.1.5 on 2021-12-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0107_chaptermasterftag'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassessuseranswer',
            name='user_fillup_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
