# Generated by Django 2.1.5 on 2021-12-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0108_selfassessuseranswer_user_fillup_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfassessuseranswer',
            old_name='user_fillup_answer',
            new_name='user_string_answer',
        ),
    ]
