# Generated by Django 2.1.5 on 2022-01-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0109_auto_20211227_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerexamgoals',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, null=True),
        ),
    ]
