# Generated by Django 2.1.5 on 2022-02-04 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0074_auto_20220131_1938'),
        ('content', '0113_auto_20220124_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryMentorActualPaperReplaceQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_start_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Date and Time of the Exam')),
                ('exam_end_date_time', models.DateTimeField(blank=True, null=True, verbose_name='End Date and Time of the Exam')),
                ('difficulty_level', models.IntegerField(default=5)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Batch')),
                ('chapters', models.ManyToManyField(blank=True, null=True, to='courses.Chapter')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Exam')),
                ('questions', models.ManyToManyField(blank=True, null=True, to='content.Question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
