# Generated by Django 2.1.5 on 2022-02-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0114_temporarymentoractualpaperreplacequestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarymentoractualpaperreplacequestions',
            name='show_time',
            field=models.BooleanField(default=True),
        ),
    ]
