# Generated by Django 2.1.5 on 2022-03-11 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0116_instituteclassroom_userclassroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituteclassroom',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='userclassroom',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='instituteclassroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituteclassroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='learnerexamgoals',
            name='assessment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnerexamgoals',
            name='evaluation_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userclassroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userclassroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
