# Generated by Django 2.1.5 on 2022-03-14 08:42

import ckeditor_uploader.fields
import content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0077_auto_20220309_1402'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0118_auto_20220314_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalAssessmentExamAnswerPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('practice', 'Practice'), ('paper', 'Paper')], max_length=24)),
                ('show_time', models.BooleanField(default=True)),
                ('submitted', models.BooleanField(default=False)),
                ('pregoal_paper', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date and Time of the qp')),
                ('paper_complete', models.BooleanField(default=False)),
                ('pause_count', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('attempted', models.IntegerField(default=0)),
                ('attempted_date', models.DateTimeField(blank=True, null=True)),
                ('percentage', models.IntegerField(default=0, verbose_name='Total Percentage')),
                ('time_taken', models.IntegerField(default=0, verbose_name='Number of minutes to finish paper')),
                ('total_time', models.IntegerField(default=0)),
                ('paper_count', models.IntegerField(default=0)),
                ('remaining_time', models.IntegerField(blank=True, default=0, null=True)),
                ('correct', models.IntegerField(default=0)),
                ('unchecked', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('question_order', models.TextField(blank=True, default='')),
                ('chapters', models.ManyToManyField(blank=True, null=True, to='courses.Chapter')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.LearnerExamGoals')),
                ('question_answered', models.ManyToManyField(blank=True, related_name='goal_question_answered', to='content.Question')),
                ('question_markforreview', models.ManyToManyField(blank=True, related_name='goal_question_markforreview', to='content.Question')),
                ('question_save_markforreview', models.ManyToManyField(blank=True, related_name='goal_question_save_markforreview', to='content.Question')),
                ('question_unanswered', models.ManyToManyField(blank=True, related_name='goal_question_unanswered', to='content.Question')),
                ('questions', models.ManyToManyField(blank=True, null=True, to='content.Question')),
                ('subjects', models.ManyToManyField(blank=True, null=True, to='courses.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalAssessmentPaperInstructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instruction', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoalAssessmentUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_order', models.IntegerField(default=0)),
                ('timespent', models.IntegerField(blank=True, null=True)),
                ('type_of_answer', models.CharField(max_length=24)),
                ('user_string_answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='text')),
                ('user_boolean_answer', models.BooleanField(blank=True, null=True)),
                ('user_subjective_answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='user subjective answer')),
                ('user_subjective_answer_image', models.FileField(blank=True, null=True, upload_to=content.models.user_subjective_answer_image, verbose_name='user subjective answer image')),
                ('teacher_subjective_comment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='teacher subjective comment')),
                ('status', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('answer_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.GoalAssessmentExamAnswerPaper')),
                ('correct_boolean_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_correct_boolean_answer', to='content.TrueFalseSolution')),
                ('correct_fillup_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_correct_fillup_answer', to='content.FillUpSolution')),
                ('correct_fillup_option_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_correct_fillup_option_answer', to='content.FillUpWithOption')),
                ('correct_mcq_answer', models.ManyToManyField(blank=True, related_name='goal_correct_mcq_answer', to='content.McqTestCase')),
                ('correct_string_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_correct_string_answer', to='content.StringTestCase')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_fillup_option_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_user_fillup_option_answer', to='content.FillUpWithOption')),
                ('user_mcq_answer', models.ManyToManyField(blank=True, related_name='goal_user_mcq_answer', to='content.McqTestCase')),
                ('user_subjective_answer_images', models.ManyToManyField(blank=True, to='content.UserSubjectiveAnswerImage')),
            ],
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentexamanswerpaper',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentexamanswerpaper',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentexamanswerpaper',
            name='question_answered',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentexamanswerpaper',
            name='question_markforreview',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentexamanswerpaper',
            name='question_save_markforreview',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentexamanswerpaper',
            name='question_unanswered',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentexamanswerpaper',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentexamanswerpaper',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentexamanswerpaper',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentpaperinstructions',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentuseranswer',
            name='answer_paper',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentuseranswer',
            name='correct_boolean_answer',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentuseranswer',
            name='correct_fillup_answer',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentuseranswer',
            name='correct_fillup_option_answer',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentuseranswer',
            name='correct_mcq_answer',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentuseranswer',
            name='correct_string_answer',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentuseranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentuseranswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentuseranswer',
            name='user_fillup_option_answer',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentuseranswer',
            name='user_mcq_answer',
        ),
        migrations.RemoveField(
            model_name='pregoalassessmentuseranswer',
            name='user_subjective_answer_images',
        ),
        migrations.AlterField(
            model_name='temporarypapersubjectquestiondistribution',
            name='goal_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.GoalAssessmentExamAnswerPaper'),
        ),
        migrations.DeleteModel(
            name='PreGoalAssessmentExamAnswerPaper',
        ),
        migrations.DeleteModel(
            name='PreGoalAssessmentPaperInstructions',
        ),
        migrations.DeleteModel(
            name='PreGoalAssessmentUserAnswer',
        ),
        migrations.AddField(
            model_name='goalassessmentpaperinstructions',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.GoalAssessmentUserAnswer'),
        ),
    ]
