# Generated by Django 2.1.5 on 2022-03-14 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0119_auto_20220314_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerGoalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_practice_time', models.IntegerField(default=0)),
                ('total_paper_time', models.IntegerField(default=0)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.LearnerExamGoals')),
                ('papers', models.ManyToManyField(blank=True, null=True, to='content.GoalAssessmentExamAnswerPaper')),
                ('questions', models.ManyToManyField(blank=True, to='content.Question')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearnerGoalPaperHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('percentage', models.IntegerField(default=0)),
                ('total_time', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('time_taken', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('attempted', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('unchecked', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.LearnerExamGoals')),
                ('papers', models.ManyToManyField(blank=True, null=True, to='content.GoalAssessmentExamAnswerPaper')),
                ('questions', models.ManyToManyField(blank=True, to='content.Question')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearnerGoalPracticeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('percentage', models.IntegerField(default=0)),
                ('total_time', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('time_taken', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('attempted', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('unchecked', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.LearnerExamGoals')),
                ('papers', models.ManyToManyField(blank=True, null=True, to='content.GoalAssessmentExamAnswerPaper')),
                ('questions', models.ManyToManyField(blank=True, to='content.Question')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
