# Generated by Django 2.1.5 on 2022-03-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0120_learnergoalhistory_learnergoalpaperhistory_learnergoalpracticehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalassessmentexamanswerpaper',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
