# Generated by Django 2.1.5 on 2022-03-15 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0122_remove_temporarypapersubjectquestiondistribution_goal_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarypapersubjectquestiondistribution',
            name='goal_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.GoalAssessmentExamAnswerPaper'),
        ),
    ]
