# Generated by Django 2.1.5 on 2022-03-15 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0123_temporarypapersubjectquestiondistribution_goal_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalassessmentpaperinstructions',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.GoalAssessmentExamAnswerPaper'),
        ),
    ]
