# Generated by Django 2.1.5 on 2022-03-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0124_auto_20220315_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalassessmentpaperinstructions',
            name='paper',
        ),
        migrations.DeleteModel(
            name='GoalAssessmentPaperInstructions',
        ),
    ]
