# Generated by Django 2.1.5 on 2022-03-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0134_auto_20220315_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalassessmentexamanswerpaper',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='goalassessmentexamanswerpaper',
            name='score',
        ),
    ]
