# Generated by Django 2.1.5 on 2022-03-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0136_auto_20220316_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
