# Generated by Django 2.1.5 on 2022-03-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0137_auto_20220317_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredMentorBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('institute_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.InstituteClassRoom')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='institute_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.InstituteClassRoom'),
        ),
    ]
