# Generated by Django 2.1.5 on 2022-03-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = True 

    dependencies = [
        ('courses', '0077_auto_20220309_1402'),
        ('content', '0138_auto_20220317_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalPathLearnChapterHintHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_check_date', models.DateTimeField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('chapter_hint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.ChapterHints')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoalPathLearnChapterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.IntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoalPathReviseChapterHintHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_check_date', models.DateTimeField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('chapter_hint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.ChapterHints')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoalPathReviseChapterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.IntegerField(default=0)),
                ('frozen_date', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearnerExamGoalPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter', models.IntegerField(default=0)),
                ('previous_path_id', models.IntegerField(default=0)),
                ('next_path_id', models.IntegerField(default=0)),
                ('frozen_date', models.DateTimeField(blank=True, null=True)),
                ('freeze', models.BooleanField(default=False)),
                ('learn_percentage', models.IntegerField(default=0)),
                ('revise_percentage', models.IntegerField(default=0)),
                ('practice_percentage', models.IntegerField(default=0)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.LearnerExamGoals')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='goalassessmentexamanswerpaper',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='goalassessmentexamanswerpaper',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='goalpathrevisechapterhistory',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.LearnerExamGoalPath'),
        ),
        migrations.AddField(
            model_name='goalpathrevisechapterhinthistory',
            name='revise_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.GoalPathReviseChapterHistory'),
        ),
        migrations.AddField(
            model_name='goalpathlearnchapterhistory',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.LearnerExamGoalPath'),
        ),
        migrations.AddField(
            model_name='goalpathlearnchapterhinthistory',
            name='learn_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.GoalPathLearnChapterHistory'),
        ),
        migrations.AddField(
            model_name='goalpathlearnchapterhinthistory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalpathrevisechapterhinthistory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
