# Generated by Django 2.1.5 on 2022-04-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0139_auto_20220330_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerexamgoalpath',
            name='done_with_assessment',
            field=models.BooleanField(default=False),
        ),
    ]
