# Generated by Django 2.1.5 on 2022-04-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0077_auto_20220309_1402'),
        ('content', '0140_learnerexamgoalpath_done_with_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarypapersubjectquestiondistribution',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter'),
        ),
    ]
