# Generated by Django 2.1.5 on 2022-04-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0141_temporarypapersubjectquestiondistribution_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlanguage',
            name='short_text',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
