# Generated by Django 2.1.5 on 2022-04-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0142_questionlanguage_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerexamgoals',
            name='assessment_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
