# Generated by Django 2.1.5 on 2022-04-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0143_learnerexamgoals_assessment_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarypapersubjectquestiondistribution',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Subject'),
        ),
    ]
