# Generated by Django 2.1.5 on 2022-04-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0146_mentorfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerbatches',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
