# Generated by Django 2.1.5 on 2022-05-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0149_learnerexamgoals_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteclassroom',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
