# Generated by Django 2.1.5 on 2022-05-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0150_auto_20220502_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerquery',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnerquery',
            name='reply',
            field=models.CharField(blank=True, max_length=1100, null=True),
        ),
    ]
