# Generated by Django 2.1.5 on 2022-05-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0151_auto_20220505_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportederrorneousquestion',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportederrorneousquestion',
            name='reply',
            field=models.CharField(blank=True, max_length=1100, null=True),
        ),
    ]
