# Generated by Django 2.1.5 on 2022-05-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0152_auto_20220505_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerexamgoals',
            name='learn_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexamgoals',
            name='practice_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerexamgoals',
            name='revise_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
