# Generated by Django 2.1.5 on 2022-05-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0153_auto_20220506_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerexamgoalpath',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.LearnerPapers'),
        ),
        migrations.AddField(
            model_name='learnerpapers',
            name='goal_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='learnerpapers',
            name='is_linked_goal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnerpapers',
            name='paper_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
