# Generated by Django 2.1.5 on 2022-05-13 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0155_auto_20220509_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteclassroom',
            name='blocked_students',
            field=models.ManyToManyField(blank=True, null=True, related_name='blocked_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
