# Generated by Django 2.1.5 on 2022-05-13 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0156_instituteclassroom_blocked_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteclassroom',
            name='blocked_students',
            field=models.ManyToManyField(blank=True, related_name='blocked_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
