# Generated by Django 2.1.5 on 2022-09-30 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20220921_1804'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0161_auto_20220930_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='', max_length=100)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchschool', to='profiles.Institute')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSeasson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seassion_name', models.CharField(choices=[('1', '2020-2021'), ('2', '2021-2022'), ('3', '2022-2023'), ('4', '2023-2024'), ('5', '2024-2025')], default='1', max_length=50)),
                ('schoolbranch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.BranchSchool')),
            ],
        ),
        migrations.AlterField(
            model_name='instituteclassroom',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchname', to='content.BranchSchool'),
        ),
    ]
