# Generated by Django 2.1.5 on 2022-10-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0163_auto_20220930_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolseasson',
            name='seassion_name',
            field=models.CharField(choices=[('1', '2021-2022'), ('2', '2022-2023'), ('3', '2023-2024'), ('4', '2024-2025')], default='1', max_length=50),
        ),
    ]
