# Generated by Django 2.1.5 on 2022-10-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0164_auto_20221013_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='unique_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='instituteclassroom',
            name='unique_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
