# Generated by Django 2.1.5 on 2022-11-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0165_auto_20221027_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteclassroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
