# Generated by Django 2.1.5 on 2022-11-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userseasson'),
        ('content', '0166_instituteclassroom_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteclassroom',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserSeasson'),
        ),
        migrations.AddField(
            model_name='schoolseasson',
            name='session_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserSeasson'),
        ),
    ]
