from django.conf.urls import include, url
from django.urls import path
from rest_framework import routers

from courses.models import ChapterVideo

from . import views

router = routers.DefaultRouter()
# router.register(r'chapters', views.ChapterViewSet)
router.register(r'chapter_video', views.ChapterVideoView, base_name="chapter-video")


app_name = 'courses'
urlpatterns = [
    url(r'^', include(router.urls)),
    path('domain/', views.ExamDomainViewSet.as_view(), name='domain'),
    path('domain/<pk>/', views.EditDomainView.as_view(), name='editdomain'),
    path('alldomains/', views.AllExamDomainViewSet.as_view(), name='alldomains'),
    path('domain/exams', views.FetchDomainExamsView.as_view(), name='domainexams'),
    path('examcategory/', views.ExamCategoryViewSet.as_view(), name='examcategory'),
    path('examcategory/<pk>/', views.EditExamCategoryViewSet.as_view(), name='editexamcategory'),
    path('examlevel/', views.ExamLevelViewSet.as_view(), name='examlevel'),
    path('examlevel/<pk>/', views.EditExamLevelViewSet.as_view(), name='editexamlevel'),
    path('courses/', views.CourseViewSet.as_view(), name='courses'),
    path('courses/all/', views.AllCourseViewSet.as_view(), name='allcourses'),
    path('courses/<pk>/', views.EditCourseView.as_view(), name='editcourse'),
    path('exampathquestion/', views.ExamMakePathQuestionsViewSet.as_view(), name='exampathquestion'),
    path('exampathquestion/<pk>/', views.EditExamMakePathQuestionsView.as_view(), name='editexampathquestion'),
    path('subject/', views.SubjectViewSet.as_view(), name='subject'),
    path('subject/<pk>/', views.EditSubjectView.as_view(), name='editsubject'),
    path('allsubject/', views.AllAdminSubjectViewSet.as_view(), name='allsubject'),
    path('domainnode/', views.DomainNodeViewSet.as_view(), name='domainnode'),
    path('domainnode/<pk>/', views.EditDomainNodeView.as_view(), name='editdomainnode'),
    path('initialdomainnode/', views.InitialDomainNodeView.as_view(), name='initialdomainnode'),
    path('lastexamdomainnode/', views.LastExamDomainNodeView.as_view(), name='lastexamdomainnode'),
    path('domainnode/addexam/<pk>/', views.AddExamInDomainNodeView.as_view(), name='addexamdomainnode'),
    path('domainnode/addsuccessive/<pk>/', views.AddSuccessiveNode.as_view(), name='addsuccessive'),
    path('domainnode/delete/<pk>/', views.DeleteDomainNodeView.as_view(), name='deletedomainnode'),
    path('chapter/', views.ChapterViewSet.as_view(), name='chapter'),
    path('chapter/<pk>/', views.EditChapterViewSet.as_view(), name='editchapter'),
    path('addftagchapter/<pk>/', views.AddFTagsinChapterView.as_view(), name='addftagchapter'),
    path('removeftagchapter/<pk>/', views.RemoveFTagFromChapterView.as_view(), name='removeftagchapter'),
    path('filtertag/', views.FTagViewSet.as_view(), name='filtertag'),
    path('filtertag/<pk>/', views.EditFTagViewSetViewSet.as_view(),
         name='editfiltertag'),
    path('searchfiltertag/', views.SearchFTagViewSetViewSet.as_view(),
         name='searchfiltertag'),
    path('searchmultiplefiltertag/', views.SearchMultipleFTagsViewSetViewSet.as_view(),
         name='searchmultiplefiltertag'),
    path('searchexam/', views.SearchExamViewSet.as_view(),
         name='searchexam'),
    path('learnerexam/', views.LearnerExamViewSet.as_view(), name='learnerexam'),
    path('alllearnerexam/', views.AllLearnerExamViewSet.as_view(), name='alllearnerexam'),
    path('learnerexam/<pk>/', views.EditLearnerExamDetailQuestionsView.as_view(), name='editlearnerexam'),
    path('examquestionaveragetime/', views.ExamAverageQuestionTimeViewSet.as_view(), name='examquestionaveragetime'),
    path('examquestionaveragetime/<pk>/', views.EditAverageViewSet.as_view(), name='editexamquestionaveragetime'),
    path('examtotalstudent/', views.ExamTotalStudentsViewSet.as_view(), name='examtotalstudent'),
    path('examtotalstudent/<pk>/', views.EditExamTotalStudentsViewSet.as_view(), name='editexamtotalstudent'),
    path('examlinkedquestiontypes/', views.ExamQuestionTypeViewSet.as_view(), name='examlinkedquestiontypes'),
    path('showallexamlinkedquestiontypes/', views.ShowAllExamQuestionTypeViewSet.as_view(), name='showallexamlinkedquestiontypes'),
    path('examlinkedquestiontypes/<pk>/', views.EditExamQuestionTypeViewSet.as_view(), name='editexamlinkedquestiontypes'),
    path('domainannouncement/', views.DomainAnnouncementViewSet.as_view(), name='domainannouncement'),
    path('domainannouncement/<pk>/', views.EditDomainAnnouncementViewSet.as_view(), name='editdomainannouncement'),
    path('adminviewdomainannouncement/', views.AdminDomainAnnouncementViewSet.as_view(), name='adminviewdomainannouncement'),
    path('multipledomainannouncement/', views.FetchAnnouncementsForMultipleDomainsView.as_view(), name='multipledomainannouncement'),
    path('examsubjectwithchapters/', views.ExamSubjectsWithChaptersView.as_view(), name='examsubjectwithchapters'),
    path('exambook/', views.CreateExamBookViewSet.as_view(), name='exambook'),
    path('viewexambooks/', views.FetchExamBookViewSet.as_view(), name='viewexambook'),
    path('examuserscount/', views.FetchTotalExamLearnersCountViewSet.as_view(), name='examuserscount'),
    path('exambook/<pk>/', views.EditExamBookView.as_view(), name='editexambook'),
    path('exampreviouspaper/', views.CreateExamPreviousYearsPapersViewSet.as_view(), name='exampreviouspaper'),
    path('viewexampreviouspaper/', views.FetchExamPreviousYearsPapersViewSet.as_view(), name='viewexampreviouspaper'),
    path('exampreviouspaper/<pk>/', views.EditExamPreviousYearsPaperView.as_view(), name='editexampreviouspaper'),
    path('mentorexam/', views.MentorExamViewSet.as_view(), name='mentorexam'),
    path('mentorexam/<pk>/', views.EditMentorExamDetailQuestionsView.as_view(), name='editmentorexam'),
    path('chapterhint/', views.HintViewSet.as_view(), name='chapterhint'),
    path('chapterhint/<pk>/', views.EditChapterHintViewSetViewSet.as_view(),
         name='editchapterhint'),
    path('examalertrequest/', views.ExamStudentNotificationViewSet.as_view(), name='examalertrequest'),
    path('bulkftagupload/', views.BulkFTagUpload.as_view(), name='bulkftagupload'),
    path('domainnodedelinkexam/<pk>/', views.RemoveLinkedExamFromDomainNodeView.as_view(), name='domainnodedelinkexam'),
    path('selfassessquestion/', views.SelfAssessQuestionViewSet.as_view(), name='selfassessquestion'),
    path('selfassessquestion/<pk>/', views.EditSelfAssessQuestionViewSet.as_view(), name='editselfassessquestion'),
    path('selfassessmcqoptions/', views.MCQOptionsViewSet.as_view(), name='selfassessmcqoptions'),
    path('selfassessmcqoptions/<pk>/', views.EditMCQOptionsViewSet.as_view(), name='editselfassessmcqoptions'),
    path('bulkftagdelete/', views.BulkDeleteFTagView.as_view(), name='bulkftagdelete'),
    path('chapterallhints/', views.FetchChapterHintViewSet.as_view(), name='chapterallhints'),
    path('chapterhintdetail/<pk>/', views.DetailViewChapterHintViewSetViewSet.as_view(),
         name='chapterhintdetail'),
    path('hintconcept/', views.HintConceptViewSet.as_view(), name='hintconcept'),
    path('hintconcept/<pk>/', views.EditHintConceptViewSetViewSet.as_view(),
         name='edithintconcept'),
    path('bloomlevel/', views.BloomLevelViewSet.as_view(), name='bloomlevel'),
    path('searchexamnav/', views.SearchExamViewSetViewSet.as_view(),
         name='searchexamnav'),
    path('domainforexams/', views.ExamDomainsForExamViewSet.as_view(), name='domainforexams'),
    path('delinkalllearnerexams/', views.DelinkLearnerExamsQuestionsView.as_view(), name='delinkalllearnerexams'),
    path('selfassessquestionbank/', views.SelfAssessQuestionBankViewSet.as_view(), name='selfassessquestionbank'),
    path('selfassessexamquestion/', views.SelfAssessExamQuestionViewSet.as_view(), name='selfassessexamquestion'),
    path('selfassessexamquestion/<pk>/', views.EditSelfExamAssessQuestionViewSet.as_view(), name='editselfassessexamquestion'),
    path('delinkallmentorexams/', views.DelinkMentorExamsView.as_view(), name='delinkallmentorexams')
]